/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.khomenko.maga;

public class JavaHelloWorld {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new JavaHelloWorld().getGreeting());
    }
}
